language: node_js
node_js:
  - "4.2.4"
before_install:
  - npm install -g gulp-cli
  - npm install
after_success :
  - gulp
notifications:
  email:
    recipients:
      - anab.tn@gmail.com
    on_success: always
    on_failure: always