language: node_js
sudo: false
node_js:
- '5.4.1'

cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - npm install -g npm@3.5.3
  - npm install -g gulp-cli
after_success :
  - npm install
  - gulp build
notifications:
  email:
    recipients:
      - anab.tn@gmail.com
    on_success: always
    on_failure: always